name: dart_base16384
description: Encode binary files to printable utf16be.
version: 1.0.0
repository: https://github.com/oboard/dart_base16384

homepage: https://github.com/oboard/dart_base16384

environment:
  sdk: ^3.6.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
